import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import ModalProvider from "@/components/providers/ModalProvider"
import { cn } from "@/lib/utils";
import { SocketProvider } from "@/components/providers/SocketProvider";
const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default : "Team Chat Application",
    template : "%s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/sign-in" >
    <html lang="en">
      <body className={cn(openSans.className, "bg-white dark:bg-[#313338]")} suppressHydrationWarning>
      <ThemeProvider
         attribute="class"
         defaultTheme="dark"
         enableSystem={false}
         storageKey="discord-key"
         disableTransitionOnChange
      >
      <SocketProvider>
      <ModalProvider />
      {children}
      </SocketProvider>
      </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  );
}
